In [1]:
import hydro
import numpy as np

In [2]:
# d8_graph = np.array([[2, 2, 2, 1, 1],[2, 2, 2, 1, 1],[3, 2, 1, 4, 4],[6, 5, 4, 4, 4]])
# network = hydro.from_d8(d8_graph)

# path_to_pcraster_file = "/ec/vol/efas/static_data/5.0/ldd.nc"
# network = hydro.from_netcdf_d8(path_to_pcraster_file)

# This requires a large amount of memory
path_to_camaflood_file = "/perm/paga/cmflood/static_network_nc_v2.1/glb_01min/1min.downxy.nc"
network = hydro.from_camaflood(path_to_camaflood_file)

Catchment-finding functions

In [3]:
all_nodes = np.arange(network.n_nodes)

In [4]:
# overwrites already labelled catchments
catchments = network.catchment(all_nodes, overwrite=True)
catchments

array([0.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 5.6163276e+07,
       5.6163277e+07, 5.6163278e+07])

In [5]:
# does not overwrite already labelled catchments
catchments = network.catchment(all_nodes, overwrite=False)
catchments

array([0.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 5.6163276e+07,
       5.6163277e+07, 5.6163278e+07])

Accuflux functions

In [6]:
field = np.ones(network.n_nodes)

In [7]:
out_field = network.accuflux(field, in_place=False)
out_field

array([1., 1., 1., ..., 2., 1., 1.])

In [8]:
network.accuflux(field, in_place=True)
field

array([1., 1., 1., ..., 2., 1., 1.])