In [1]:
import hydro
import numpy as np

In [2]:
# d8_graph = np.array([[2, 2, 2, 1, 1],[2, 2, 2, 1, 1],[3, 2, 1, 4, 4],[6, 5, 4, 4, 4]])
# network = hydro.from_d8(d8_graph)

path_to_pcraster_file = "/ec/vol/efas/static_data/5.0/ldd.nc"
network = hydro.from_netcdf_d8(path_to_pcraster_file)

# This requires a large amount of memory
# path_to_camaflood_file = "/perm/paga/cmflood/static_network_nc_v2.1/glb_01min/1min.downxy.nc"
# network = hydro.from_camaflood(path_to_camaflood_file)

In [10]:
catchments = network.catchment(np.arange(network.n_nodes), overwrite=True)

array([1.000000e+00, 4.000000e+00, 3.000000e+00, ..., 7.442266e+06,
       7.442266e+06, 7.442266e+06])

In [4]:
field = np.ones(network.n_nodes)

In [5]:
out_field = network.accuflux(field, in_place=False)

In [6]:
field = np.ones(network.n_nodes)

In [7]:
network.accuflux(field, in_place=True)

array([1., 1., 1., ..., 2., 1., 1.])

In [8]:
print(out_field[0:10])

[ 1.  1.  1. 21. 14.  4.  3.  2.  1.  1.]
